Rationalize BASEDIR/TOP/PREFIX/DIR

diff --git a/sbin/attest-enroll b/sbin/attest-enroll
--- a/sbin/attest-enroll
+++ b/sbin/attest-enroll
@@ -13,26 +13,35 @@ set -euo pipefail
 shopt -s extglob
 
 PROG=${0##*/}
-if [[ $0 = /* ]]; then
-	BASEDIR=${0%/*}
-elif [[ $0 = */* ]]; then
-	BASEDIR=$PWD/${0%/*}
+BINDIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
+TOP=$(dirname "$BINDIR")
+
+if [[ -s $TOP/lib/safeboot/functions.sh ]]; then
+	# shellcheck source=functions.sh
+	. "$TOP/lib/safeboot/functions.sh"
+elif [[ -s $TOP/functions.sh ]]; then
+	# shellcheck source=functions.sh
+	. "$TOP/functions.sh"
 else
-	BASEDIR=$PWD
+	echo "Unable to find Safeboot function library" 1>&2
+	exit 1
 fi
 
 # Make sure to export SAFEBOOT_ENROLL_CONF for external genprogs
 #
 # If one or more -C options given, use the first one for this (see getopts
 # loop below).
-export SAFEBOOT_ENROLL_CONF=/etc/safeboot-enroll.conf
-CONF=$SAFEBOOT_ENROLL_CONF
+cf=$(safeboot_file etc safeboot.conf)
+if [[ -n $cf && -f $cf ]]; then
+	export SAFEBOOT_ENROLL_CONF=/etc/safeboot/enroll.conf
+	CONF=$SAFEBOOT_ENROLL_CONF
+fi
 configured=false
 
 EKPUB=/dev/stdin
 
 # Configuration variables
-DBDIR="$BASEDIR/build/attest"
+DBDIR="$TOP/build/attest"
 POLICY=
 ESCROW_POLICY=
 ESCROW_PUBS_DIR=
@@ -80,9 +89,6 @@ configs() {
 		echo
 	done
 }
-
-# shellcheck disable=SC1090
-. "$BASEDIR/../functions.sh"
 
 die() { echo >&2 "Error: $PROG" "$@" ; exit 1 ; }
 warn() { echo >&2 "$@" ; }
diff --git a/sbin/gencert b/sbin/gencert
--- a/sbin/gencert
+++ b/sbin/gencert
@@ -6,12 +6,18 @@ set -euo pipefail
 shopt -s extglob
 
 PROG=${0##*/}
-if [[ $0 = /* ]]; then
-	BASEDIR=${0%/*}
-elif [[ $0 = */* ]]; then
-	BASEDIR=$PWD/${0%/*}
+BINDIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
+TOP=$(dirname "$BINDIR")
+
+if [[ -s $TOP/lib/safeboot/functions.sh ]]; then
+	# shellcheck disable=SC1090 source=functions.sh
+	. "$TOP/lib/safeboot/functions.sh"
+elif [[ -s $TOP/functions.sh ]]; then
+	# shellcheck disable=SC1090 source=functions.sh
+	. "$TOP/functions.sh"
 else
-	BASEDIR=$PWD
+	echo "Unable to find Safeboot function library" 1>&2
+	exit 1
 fi
 
 GENCERT_CRED=PEM-FILE:/etc/safeboot/gencert-ca.pem
@@ -22,13 +28,12 @@ GENCERT_INCLUDE_SAN_DNSNAME=false
 GENCERT_EKUS=()
 declare -A GENCERT_DOMAIN_REALM
 
-: "${SAFEBOOT_ENROLL_CONF:=/etc/safeboot-enroll.conf}"
-# shellcheck disable=SC1090
-[[ -n $SAFEBOOT_ENROLL_CONF && -f $SAFEBOOT_ENROLL_CONF ]] \
-&& . "${SAFEBOOT_ENROLL_CONF}"
-
-# shellcheck disable=SC1090
-. "$BASEDIR/../functions.sh"
+cf=$(safeboot_file etc enroll.conf)
+if [[ -n $cf && -f $cf ]]; then
+	# shellcheck disable=SC1090
+	. "$cf"
+	export SAFEBOOT_ENROLL_CONF="$cf"
+fi
 
 die() { echo "skip: $*"; echo >&2 "Error: $PROG" "$@" ; exit 1 ; }
 warn() { echo >&2 "$@" ; }
diff --git a/sbin/safeboot b/sbin/safeboot
--- a/sbin/safeboot
+++ b/sbin/safeboot
@@ -24,35 +24,49 @@
 set -e -o pipefail
 export LC_ALL=C
 
-: "${PREFIX:=}"
-: "${DIR:=/etc/safeboot}"
+BINDIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
+TOP=$(dirname "$BINDIR")
 
-# shellcheck source=functions.sh
-. "$PREFIX$DIR/functions.sh"
-
-if [ -r "$PREFIX$DIR/safeboot.conf" ]; then
-	# shellcheck source=safeboot.conf
-	. $PREFIX$DIR/safeboot.conf
+if [[ -s $TOP/lib/safeboot/functions.sh ]]; then
+	# shellcheck source=functions.sh
+	. "$TOP/lib/safeboot/functions.sh"
+elif [[ -s $TOP/functions.sh ]]; then
+	# shellcheck source=functions.sh
+	. "$TOP/functions.sh"
 else
-	warn "$PREFIX$DIR/safeboot.conf not present; was it installed?"
-fi
-if [ -r "$PREFIX$DIR/local.conf" ]; then
-	# shellcheck source=local.conf
-	. $PREFIX$DIR/local.conf
+	echo "Unable to find Safeboot function library" 1>&2
+	exit 1
 fi
 
-# Apply $PREFIX to files and use default value
-CERT=$PREFIX${CERT:-$DIR/cert.pem}
-KERNEL=$PREFIX${KERNEL:-/boot/vmlinuz}
-INITRD=$PREFIX${INITRD:-/boot/initrd.img}
-EFIDIR=$PREFIX${EFIDIR:-/boot/efi/EFI}
+: "${PREFIX:=}"
+cf=$(safeboot_file etc safeboot.conf)
+if [[ -n $cf && -f $cf ]]; then
+	# shellcheck disable=SC1090
+	. "$cf"
+	export SAFEBOOT_CONF="$cf"
+else
+	warn "${cf:-/etc/safeboot/safeboot.conf} not present; was it installed?"
+fi
+cf=$(safeboot_file etc local.conf)
+if [[ -n $cf && -f $cf ]]; then
+	# shellcheck disable=SC1090
+	. "$cf"
+fi
+: "${DIR:="$(safeboot_dir etc)"}"
+
+setup
+
+: "${KERNEL:=/boot/vmlinuz}"
+: "${INITRD:=/boot/initrd.img}"
+: "${EFIDIR:=/boot/efi/EFI}"
+:   "${CERT:=$DIR/cert.pem}"
 
 if [ "$KEY" == "pkcs11:" ]; then
 	# KEY is a hardware token, use the yubikey engine
 	KEY_ENGINE="-e pkcs11"
 else
 	# KEY is a normal file, don't use an openssl engine
-	KEY=$PREFIX${KEY:-$DIR/cert.priv}
+	KEY=${KEY:-$DIR/cert.priv}
 	KEY_ENGINE=""
 fi
 
@@ -89,7 +103,7 @@ rootdev-check()
 	fi
 
 	if [ "$TEST_ROOTDEV" = 1 ]; then
-		warn "$PREFXI$DIR/local.conf: setting \$ROOTDEV=$ROOTDEV"
+		warn "$PREFIX$DIR/local.conf: setting \$ROOTDEV=$ROOTDEV"
 		echo "ROOTDEV=\"$ROOTDEV\"" >> $PREFIX$DIR/local.conf \
 		|| die "$PREFIX$DIR/local.conf: Unable to set \$ROOTDEV"
 		TEST_ROOTDEV=0
@@ -114,7 +128,7 @@ rootdev-check()
 	fi
 
 	if [ "$TEST_HASHDEV" = 1 ]; then
-		warn "$PREFXI$DIR/local.conf: setting \$HASHDEV=$HASHDEV"
+		warn "$PREFIX$DIR/local.conf: setting \$HASHDEV=$HASHDEV"
 		echo "HASHDEV=\"$HASHDEV\"" >> $PREFIX$DIR/local.conf \
 		|| die "$PREFIX$DIR/local.conf: Unable to set \$HASHDEV"
 		TEST_HASHDEV=0
diff --git a/sbin/tpm2-attest b/sbin/tpm2-attest
--- a/sbin/tpm2-attest
+++ b/sbin/tpm2-attest
@@ -20,21 +20,36 @@ export LC_ALL=C
 unset CDPATH
 
 # Find the directory that contains functions.sh
-TOP="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && cd .. && pwd )"
 
+BINDIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
+TOP=$(dirname "$BINDIR")
+
+if [[ -s $TOP/lib/safeboot/functions.sh ]]; then
+	# shellcheck source=functions.sh
+	. "$TOP/lib/safeboot/functions.sh"
+elif [[ -s $TOP/functions.sh ]]; then
+	# shellcheck source=functions.sh
+	. "$TOP/functions.sh"
+else
+	echo "Unable to find Safeboot function library" 1>&2
+	exit 1
+fi
+
+cf=$(safeboot_file etc safeboot.conf)
+if [[ -n $cf && -f $cf ]]; then
+	# shellcheck disable=SC1090
+	. "$cf"
+	export SAFEBOOT_CONF="$cf"
+fi
+cf=$(safeboot_file etc local.conf)
+if [[ -n $cf && -f $cf ]]; then
+	# shellcheck disable=SC1090
+	. "$cf"
+fi
 : "${PREFIX:=}"
 : "${DIR:=/etc/safeboot}"
 
-. "$TOP/functions.sh"
-
-if [ -r "$PREFIX$DIR/safeboot.conf" ]; then
-	. $PREFIX$DIR/safeboot.conf
-else
-	warn "$PREFIX$DIR/safeboot.conf not present?"
-fi
-if [ -r "$PREFIX$DIR/local.conf" ]; then
-	. $PREFIX$DIR/local.conf
-fi
+setup
 
 # Apply $PREFIX to files and use default value
 [[ -n ${CERT:-} && ${CERT} != /* ]]	\
diff --git a/sbin/tpm2-recv b/sbin/tpm2-recv
--- a/sbin/tpm2-recv
+++ b/sbin/tpm2-recv
@@ -1,12 +1,18 @@
 #!/bin/bash
 
 PROG=${0##*/}
-if [[ $0 = /* ]]; then
-        BASEDIR=${0%/*}
-elif [[ $0 = */* ]]; then
-        BASEDIR=$PWD/${0%/*}
+BINDIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
+TOP=$(dirname "$BINDIR")
+
+if [[ -s $TOP/lib/safeboot/functions.sh ]]; then
+	# shellcheck disable=SC1090 source=functions.sh
+	. "$TOP/lib/safeboot/functions.sh"
+elif [[ -s $TOP/functions.sh ]]; then
+	# shellcheck disable=SC1090 source=functions.sh
+	. "$TOP/functions.sh"
 else
-        BASEDIR=$PWD
+	echo "Unable to find Safeboot function library" 1>&2
+	exit 1
 fi
 
 set -euo pipefail
@@ -45,9 +51,6 @@ Usage: $PROG CIPHERTEXT OUT [POLICY-CMD [ARGS] [;] ...]
 EOF
 	exit 1
 }
-
-# shellcheck disable=SC1090
-. "$BASEDIR/../functions.sh"
 
 force=false
 while getopts +:hfx opt; do
