attest-enroll: Start a temp SW TPM for PEM case
We should be able to consume PEM and not have to convert it to
TPM2B_PUBLIC.  However, the tpm2-tools {tpm2 makecredential} and
{tpm2 duplicate} commands can't handle that, and we use those in
sbin/tpm2-send.

For now we start an SW TPM per-invocation, and tear it down when
exiting.

diff --git a/sbin/attest-enroll b/sbin/attest-enroll
--- a/sbin/attest-enroll
+++ b/sbin/attest-enroll
@@ -440,6 +440,7 @@ done
 
 tmp=
 success=false
+swtpm_pid=
 cleanup() {
 	if ((VERBOSE > 1)); then
 		(
@@ -447,6 +448,14 @@ cleanup() {
 		sha256sum "$tmp"/*
 		) | sort
 	fi
+
+	(
+		[[ -n $swtpm_pid ]]	\
+		&& kill -0 "$swtpm_pid"	\
+		&& kill "$swtpm_pid"
+	) 2>/dev/null			\
+	|| true
+	unset TPM2TOOLS_TCTI
 
 	if $debug; then
 		echo "LEAVING TEMP DIR ALONE: $tmp" 1>&2
@@ -459,6 +468,66 @@ cleanup() {
 }
 tmp="$(mktemp -d)"
 trap cleanup EXIT
+
+# We might need a TPM for what should be software-only things...
+start_swtpm() {
+	local -i tries port start ready
+	((port= 10240 + ( ($$ % (32768 - 10240) ) ) ))
+	mkdir "${tmp}/swtpm"
+
+	start=$SECONDS
+	for ((tries=0, ready=0;
+	      ready == 0 && tries < 3 && (SECONDS - start) < 10;
+	      tries++, port+=2)); do
+
+		# swtpm --daemon exits immediately, which can be too soon.
+		swtpm socket							\
+			--tpm2							\
+			--tpmstate dir="${tmp}/swtpm"				\
+			--pid file="${tmp}/.pid"				\
+			--server type="tcp,bindaddr=127.0.0.1,port=$port"	\
+			--ctrl type="tcp,bindaddr=127.0.0.1,port=$((port+1))"	\
+			--flags startup-clear					&
+		swtpm_pid=$!
+
+		# Wait until swtpm is started and running
+		while ! lsof				\
+				-p "$swtpm_pid"		\
+				-a			\
+				-i ":$port"		\
+				-a			\
+				-i ":$((port+1))" >/dev/null 2>&1; do
+
+			# Is it still running?
+			kill -0 "$swtpm_pid" || break
+
+			# Have we waited too long?
+			(( (SECONDS - start) >= 10 )) && break
+
+			sleep 1
+		done
+
+		# Check that $swtpm_pid has the two ports open
+		lsof					\
+			-p "$swtpm_pid"			\
+			-a				\
+			-i ":$port"			\
+			-a				\
+			-i ":$((port+1))"		\
+			>/dev/null 2>&1
+		&& break
+
+		# Nope; retry.  Note that at this point $swtpm_pid would be
+		# alive or a zombie, so it's OK to kill it.
+		kill "$swtpm_pid"
+		wait "$swtpm_pid"
+		swtpm_pid=
+	done
+
+	[[ -n $swtpm_pid ]]	\
+	|| die "Could not start a software TPM"
+	export TPM2TOOLS_TCTI="swtpm:host=127.0.0.1,port=$port"
+}
 
 info() {
 	((VERBOSE == 0)) || echo info: "$@" 1>&2
@@ -586,6 +655,8 @@ sign() {
 		-in <(sha256 < "$1" | hex2bin)				\
 		-out "${1}.sig"
 }
+
+start_swtpm
 
 cat "$EKPUB" > "$tmp/ekpub" \
 || die "$0: unable to read EKpub from stdin"
