Rationalize BASEDIR/TOP/PREFIX/DIR

diff --git a/sbin/genkeytab b/sbin/genkeytab
--- a/sbin/genkeytab
+++ b/sbin/genkeytab
@@ -6,12 +6,18 @@ set -euo pipefail
 shopt -s extglob
 
 PROG=${0##*/}
-if [[ $0 = /* ]]; then
-	BASEDIR=${0%/*}
-elif [[ $0 = */* ]]; then
-	BASEDIR=$PWD/${0%/*}
+BINDIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
+TOP=$(dirname "$BINDIR")
+
+if [[ -s $TOP/lib/safeboot/functions.sh ]]; then
+	# shellcheck disable=SC1090 source=functions.sh
+	. "$TOP/lib/safeboot/functions.sh"
+elif [[ -s $TOP/functions.sh ]]; then
+	# shellcheck disable=SC1090 source=functions.sh
+	. "$TOP/functions.sh"
 else
-	BASEDIR=$PWD
+	echo "Unable to find Safeboot function library" 1>&2
+	exit 1
 fi
 
 # Keytab gen methods:
@@ -36,13 +42,13 @@ curl_opts=(
 		--negotiate
 )
 
-: "${SAFEBOOT_ENROLL_CONF:=/etc/safeboot-enroll.conf}"
-# shellcheck disable=SC1090
-[[ -n $SAFEBOOT_ENROLL_CONF && -f $SAFEBOOT_ENROLL_CONF ]] \
-&& . "${SAFEBOOT_ENROLL_CONF}"
 
-# shellcheck disable=SC1090
-. "$BASEDIR/../functions.sh"
+cf=$(safeboot_file etc enroll.conf)
+if [[ -n $cf && -f $cf ]]; then
+	# shellcheck disable=SC1090
+	. "$cf"
+	export SAFEBOOT_ENROLL_CONF="$cf"
+fi
 
 die() { echo >&2 "Error: $PROG" "$@" ; exit 1 ; }
 warn() { echo >&2 "$@" ; }
diff --git a/sbin/getkeytab b/sbin/getkeytab
--- a/sbin/getkeytab
+++ b/sbin/getkeytab
@@ -7,7 +7,20 @@ shopt -s extglob
 umask 077
 
 PROG=${0##*/}
-BASEDIR=$(dirname "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )")
+BINDIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
+TOP=$(dirname "$BINDIR")
+
+if [[ -s $TOP/lib/safeboot/functions.sh ]]; then
+	# shellcheck disable=SC1090 source=functions.sh
+	. "$TOP/lib/safeboot/functions.sh"
+elif [[ -s $TOP/functions.sh ]]; then
+	# shellcheck disable=SC1090 source=functions.sh
+	. "$TOP/functions.sh"
+else
+	echo "Unable to find Safeboot function library" 1>&2
+	exit 1
+fi
+
 
 declare -A GETCERT_DOMAIN_REALM
 KEYTAB=FILE:/etc/krb5.keytab
@@ -23,19 +36,23 @@ curl_opts=(
 	--negotiate
 )
 
-: "${PREFIX:=}"
-: "${DIR:=/etc/safeboot}"
-SAFEBOOT_CONF=${PREFIX}${DIR}/safeboot.conf
-# shellcheck disable=SC1090
-[[ -n $SAFEBOOT_CONF && -f $SAFEBOOT_CONF ]]	\
-&& . "${SAFEBOOT_CONF}"
+cf=$(safeboot_file etc safeboot.conf)
+if [[ -n $cf && -f $cf ]]; then
+	# shellcheck disable=SC1090
+	. "$cf"
+	export SAFEBOOT_CONF="$cf"
+else
+	warn "${cf:-/etc/safeboot/safeboot.conf} not present; was it installed?"
+fi
+cf=$(safeboot_file etc local.conf)
+if [[ -n $cf && -f $cf ]]; then
+	# shellcheck disable=SC1090
+	. "$cf"
+fi
+DIR=$(safeboot_dir etc)
 
-# shellcheck disable=SC1090
-. "$BASEDIR/../functions.sh"
-
-: "${CERT_KEY:=${PREFIX}${DIR}/cert-key.pem}"
-: "${CERT:=${PREFIX}${DIR}/cert.pem}"
-
+: "${CERT_KEY:=${DIR}/cert-key.pem}"
+: "${CERT:=${DIR}/cert.pem}"
 [[ -f $CERT_KEY &&  -f $CERT ]]			\
 || die "Could not get PKINIT certificate for impersonation"
 
diff --git a/sbin/tpm2-policy b/sbin/tpm2-policy
--- a/sbin/tpm2-policy
+++ b/sbin/tpm2-policy
@@ -1,13 +1,20 @@
 #!/bin/bash
 
 PROG=${0##*/}
+BINDIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
+TOP=$(dirname "$BINDIR")
 
-if [[ $0 = /* ]]; then
-        BASEDIR=${0%/*}
-elif [[ $0 = */* ]]; then
-        BASEDIR=$PWD/${0%/*}
+if [[ -s $TOP/lib/safeboot/functions.sh ]]; then
+	# shellcheck disable=SC1090 source=functions.sh
+	. "$TOP/lib/safeboot/functions.sh"
+	functions_sh=$TOP/lib/safeboot/functions.sh
+elif [[ -s $TOP/functions.sh ]]; then
+	# shellcheck disable=SC1090 source=functions.sh
+	. "$TOP/functions.sh"
+	functions_sh=$TOP/functions.sh
 else
-        BASEDIR=$PWD
+	echo "Unable to find Safeboot function library" 1>&2
+	exit 1
 fi
 
 set -euo pipefail -o noclobber
@@ -39,9 +46,6 @@ Usage: $PROG [-o FILE] [-A | -D] POLICY-CMD [ARGS [\\; ...]]
 EOF
 	exit "${1:-1}"
 }
-
-# shellcheck disable=SC1090
-. "$BASEDIR/../functions.sh"
 
 out=
 force=false
