extend TPM PCR14 with boot mode

diff --git a/sbin/safeboot b/sbin/safeboot
--- a/sbin/safeboot
+++ b/sbin/safeboot
@@ -26,6 +26,18 @@ TMP=`mktemp -d`
 TMP_MOUNT=n
 trap cleanup EXIT
 
+hex2bin() { perl -ne 'chomp; print pack("H*", $_)' ; }
+sha256() { sha256sum - | cut -d' ' -f1 ; }
+PCR_DEFAULT=0000000000000000000000000000000000000000000000000000000000000000
+
+#
+# Compute the extended value of a PCR register
+#
+tpm2_trial_extend() {
+	( echo -n "$1" ; sha256 ) | hex2bin | sha256
+}
+
+
 usage="Safe Boot subcommands:
 ----
 "
@@ -248,9 +260,14 @@ luks-seal() {
 		>> /tmp/tpm.log \
 	|| die "Unable to read TPM PCRs"
 
-	# Add a zero entry for PCR 14, which ensures that the system
-	# will not be able to unseal the secret after the initial unsealing
-	perl -e 'print chr(0x00) x 0x20' >> "$TMP/pcrs.bin"
+	# Add a "normal" entry for PCR 14, which ensures that the TPM
+	# will only unseal during a normal boot, not a recovery boot.
+	# the unseal script will also extend PCR14 after unsealing
+	# to prevent the TPM from unsealing the secret a second time
+	echo -n "normal" \
+		| tpm2_trial_extend $PCR_DEFAULT \
+		| hex2bin \
+		>> "$TMP/pcrs.bin"
 
 	tpm2_createpolicy \
 		--policy-pcr \
@@ -455,6 +472,12 @@ sign-kernel() {
 
 	echo "Kernel commandline: '`cat $TMP/cmdline.txt`'"
 	sha256sum "$OUTDIR/linux.efi"
+
+	if [ -r "$TMP/verity.log" ]; then
+		# stash a copy of the verity log in the boot directory
+		# so that repeat signing can be done more quickly
+		cp "$TMP/verity.log" "$OUTDIR"
+	fi
 }
 
 hash_and_sign_usage="
@@ -483,7 +506,7 @@ hash-and-sign()
 
 	if mount | grep "${ROOTDEV}" ; then \
 		warn "$ROOTDEV: unmounting and checking"
-		mount -o ro,noload,noatime,remount "${ROOTDEV}" ; \
+		mount -o ro,noatime,remount "${ROOTDEV}" ; \
 		fsck.ext4 -f "${ROOTDEV}"
 	fi
 
@@ -510,12 +533,14 @@ hash-and-sign()
 		/boot/initrd.img \
 		root=/dev/mapper/vroot \
 		ro \
+		fsck.mode=skip \
 		verity.hashdev="${HASHDEV}" \
 		verity.rootdev="${ROOTDEV}" \
 		verity.hash="$HASH" \
 		tpm.pcrs=0,2,5,7,14 \
-		"$@"
-
+		tpm.mode=normal \
+		"$@" \
+	|| die "Kernel signing failed!"
 }
 
 
diff --git a/sbin/safeboot-tpm-unseal b/sbin/safeboot-tpm-unseal
--- a/sbin/safeboot-tpm-unseal
+++ b/sbin/safeboot-tpm-unseal
@@ -1,4 +1,4 @@
-#!/bin/sh -x
+#!/bin/sh
 # This is run in the initramfs context, not in the normal user space.
 # It attempts to unseal the key from the TPM based on the PCRS passed
 # on the command line using direct access since there is no resource
@@ -12,28 +12,63 @@
 #
 source /scripts/functions
 
-# HACK: the PCRs should be read from the kernel command line
-PCRS='sha256:0,2,5,7,14'
+# Default PCRs
+PCRS='0,2,5,7,14'
+MODE=unknown
 HANDLE=0x81000000
+
+# Direct access
 export TPM2TSSENGINE_TCTI="device:/dev/tpmrm0"
 
-log_begin_msg "Reading TPM PCRs"
-/usr/bin/tpm2_pcrread >&2 \
-	'sha256:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16' \
+for arg in $(cat /proc/cmdline)
+do
+    case "$arg" in
+        tpm.mode=*)
+            MODE=${arg#tpm.mode=}
+            ;;
+        tpm.pcrs=*)
+            PCRS=${arg#tpm.pcrs=}
+            ;;
+        tpm.handle=*)
+            HANDLE=${arg#tpm.handle=}
+            ;;
+        *)
+            ;;
+    esac
+done
 
+log_begin_msg "TPM mode=$MODE pcrs=$PCRS"
+
+sha256() { echo -n "$@" | sha256sum | cut -d' ' -f1 ; }
+
+/usr/bin/tpm2_pcrread >&2 \
+	'sha256:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16'
+
+#
+# Extend PCR14 with the boot mode so that recovery
+# boots aren't able to access the sealed disk key.
+#
+/usr/bin/tpm2_pcrextend >&2 14:sha256=`sha256 "$MODE"`
+
+
+#
+# Attempt to unseal, outputing the binary key to stdout
+#
 if /usr/bin/tpm2_unseal \
-	--object-context $HANDLE \
-	--auth pcr:"$PCRS" \
+	--object-context "$HANDLE" \
+	--auth pcr:"sha256:$PCRS" \
 ; then
 	# ensure that a local attacker can't re-read the key from the TPM
-	# by setting pcr 14 to "postboot"
-	/usr/bin/tpm2_pcrextend >&2 \
-		14:sha256=35675e73484c1191b3c0eabe782d8634d35f17fdf632f73cd5360c1bcb133855
-
-	log_success_msg "Disk key unsealed"
+	# by extending pcr 14 with "postboot"
+	log_success_msg "TPM disk key unsealed"
+	/usr/bin/tpm2_pcrextend >&2 14:sha256=`sha256 postboot`
+	exit 0
 else
-	# the key was not unsealed; ask the user for it
+	# the key was not unsealed; log the failure
+	# and ask the user for the recovery key
 	log_failure_msg "Falling back to user pass phrase"
+	/usr/bin/tpm2_pcrextend >&2 14:sha256=`sha256 bootfail`
+
 	/lib/cryptsetup/askpass \
 		"TPM Unsealing failed! Enter recovery key for $CRYPTTAB_SOURCE ($CRYPTTAB_NAME): "
 fi
