$HASHDEV: set the hash device in local.conf at end of sip-init (#34)
Signed-off-by: Trammell hudson <hudson@trmm.net>

diff --git a/sbin/safeboot b/sbin/safeboot
--- a/sbin/safeboot
+++ b/sbin/safeboot
@@ -1154,13 +1154,6 @@ you can unwind the changes that were made.
 	lvcreate --size 1g -n hashes "$vg" \
 	|| die "$vg-hashes: unable to create volume"
 
-	if [ -z "$HASHDEV" ]; then
-		HASHDEV="/dev/mapper/$vg-hashes"
-		warn "$PREFIX$DIR/local.conf: adding HASHDEV=$HASHDEV"
-		echo "HASHDEV=\"$HASHDEV\"" >> "$PREFIX$DIR/local.conf" \
-		|| die "$PREFIX$DIR/local.conf: unable to add HASHDEV"
-	fi
-
 	lvcreate --size "$var_size" -n var "$vg" \
 	|| die "$vg-var: unable to create volume"
 
@@ -1211,7 +1204,14 @@ you can unwind the changes that were made.
 		|| die "$PREFIX$DIR/safeboot.conf: unable to enable SIP?"
 	fi
 
-	warn "${ROOTDEV}: now configured for SIP, but not yet signed!"
+	if [ -z "$HASHDEV" ]; then
+		HASHDEV="/dev/mapper/$vg-hashes"
+		warn "$PREFIX$DIR/local.conf: adding HASHDEV=$HASHDEV"
+		echo "HASHDEV=\"$HASHDEV\"" >> "$PREFIX$DIR/local.conf" \
+		|| die "$PREFIX$DIR/local.conf: unable to add HASHDEV"
+	fi
+
+	warn "${ROOTDEV}: now configured for SIP hashed on ${HASHDEV}, but not yet signed!"
 	warn "${ROOTDEV}: reboot and immediately run 'safeboot linux-sign'"
 }
 
