tpm-unseal: use functions.sh for tpm policy creation

diff --git a/sbin/safeboot-tpm-unseal b/sbin/safeboot-tpm-unseal
--- a/sbin/safeboot-tpm-unseal
+++ b/sbin/safeboot-tpm-unseal
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # This is run in the initramfs context, not in the normal user space.
 # The boot mode should have been extended in the start of the initramfs.
 #
@@ -18,19 +18,18 @@
 PCRS=0
 BOOTMODE_PCR=14
 MODE=unknown
+if [ -z "$DIR" ]; then
+	DIR="/etc/safeboot"
+fi
 
-[ -r "/etc/safeboot/safeboot.conf" ] && . "/etc/safeboot/safeboot.conf"
-[ -r "/etc/safeboot/local.conf" ] && . "/etc/safeboot/local.conf"
+for script in safeboot.conf local.conf functions.sh ; do
+	[ -r "$DIR/$script" ] && . "$DIR/$script"
+done
 
-# Direct access to the kernel resource manager
-# since there is no standalone TPM resource manager in the initrd
-export TPM2TOOLS_TCTI="device:/dev/tpmrm0"
-
-sha256() { echo -n "$@" | sha256sum | cut -d' ' -f1 ; }
-log() { echo >&2 "$@" ; }
+# Override die to extend the boot mode PCR to indicate the failure
 die() {
 	echo >&2 "$@"
-	/usr/sbin/tpm2 pcrextend >&2 "$BOOTMODE_PCR:sha256=$(sha256 bootfail)"
+	tpm2 pcrextend >&2 "$BOOTMODE_PCR:sha256=$(echo bootfail | sha256)"
 	touch "/tmp/unseal-failed"
 	exit 1
 }
@@ -47,15 +46,15 @@ do
     esac
 done
 
-log "TPM mode=$MODE pcrs=$PCRS $BOOTMODE_PCR"
+warn "TPM mode=$MODE pcrs=$PCRS $BOOTMODE_PCR"
 
-/usr/sbin/tpm2 pcrread >&2 \
+tpm2 pcrread >&2 \
 	'sha256:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16'
 
 if [ "$MODE" = "recovery" ] \
 || [ -r "/tmp/unseal-failed" ] \
 ; then
-	log "Falling back to user pass phrase"
+	warn "Falling back to user pass phrase"
 
 	# retrieve a tpmtotp attestation so that the user knows
 	# that the firmware is unmodified and that it is safe to
@@ -70,87 +69,19 @@ Enter recovery key for $CRYPTTAB_SOURCE ($CRYPTTAB_NAME): "
 fi
 
 #
-# This is not a recovery boot, try to unseal the secret using the TPM
-# and optional user PIN.
+# This is not a recovery boot, try to unseal the secret using the TPM,
+# the current NV version and optional user PIN.
 #
-tpm2 flushcontext --transient-object
-tpm2 flushcontext --loaded-session
-
-log "TPM: Starting auth session"
-tpm2 startauthsession \
-	--policy-session \
-	--session "/tmp/session.ctx" \
-	>> /tmp/tpm.log \
-|| die "Unable to start policy session"
-
-tpm2 policypcr \
-	--session "/tmp/session.ctx" \
-	--pcr-list "sha256:$PCRS,$BOOTMODE_PCR" \
-	--policy "/tmp/pcr.policy" \
-	>> /tmp/tpm.log \
-|| die "Unable to create PCR policy"
-
-if [ "$SEAL_PIN" = "1" ]; then
-	# Add an auth value, which will require the PIN for unsealing
-	tpm2 policyauthvalue \
-		--session "/tmp/session.ctx" \
-		--policy "/tmp/pcr.policy" \
-		>> /tmp/tpm.log \
-	|| die "Unable to create auth value policy"
-fi
-
-tpm2 nvread "$TPM_NV_VERSION" \
-| tpm2 policynv \
-	--session "/tmp/session.ctx" \
-	"$TPM_NV_VERSION" eq \
-	--input "-" \
-	--policy "/tmp/pcr.policy" \
-	>> /tmp/tpm.log \
-|| die "Unable to load TPM version counter"
-
-log "TPM: Loading RSA public key"
-tpm2 loadexternal \
-	--key-algorithm rsa \
-	--hierarchy owner \
-	--public "/etc/safeboot/cert.pub" \
-	--key-context "/tmp/key.ctx" \
-	--name "/tmp/key.name" \
-	>> /tmp/tpm.log \
-|| die "Unable to load platform key"
-
 # Extract the signature from the UEFI variable, skipping
 # the four-byte UEFI variable header.
-if ! mount | grep -q /sys/firmware/efi/efivars ; then
-	mount -t efivarfs efivarfs /sys/firmware/efi/efivars \
-	|| die "Unable to mount EFI var filesystem"
-fi
 
-cat "/sys/firmware/efi/efivars/$PCR_SIGNATURE" > /tmp/efivar.bin \
-|| die "Unable to read PCR signature from $PCR_SIGNATURE"
+VERSION="$(tpm2 nvread "$TPM_NV_VERSION" | bin2hex)"
+TPM_SESSION_TYPE=policy
+TPM_POLICY_SIG="$TMP/pcr.policy.sig"
 
-tail \
-	-c +5 \
-	< "/tmp/efivar.bin" \
-	> "/tmp/pcr.policy.sig" \
-|| die "Unable to read PCR signature from $PCR_SIGNATURE"
+efivar-read "$PCR_SIGNATURE" > "$TPM_POLICY_SIG"
 
-tpm2 verifysignature \
-	--hash-algorithm sha256 \
-	--scheme rsassa \
-	--key-context "/tmp/key.ctx" \
-	--message "/tmp/pcr.policy" \
-	--signature "/tmp/pcr.policy.sig" \
-	--ticket "/tmp/pcr.policy.tkt" \
-	>> /tmp/tpm.log \
-|| die "Unable to verify PCR signature"
-
-tpm2 policyauthorize \
-	--session "/tmp/session.ctx" \
-	--name "/tmp/key.name" \
-	--input "/tmp/pcr.policy" \
-	--ticket "/tmp/pcr.policy.tkt" \
-	>> /tmp/tpm.log \
-|| die "Unable to authorize ticket"
+tpm2_create_policy "" "$VERSION"
 
 tpm2 flushcontext --transient-object
 
@@ -165,8 +96,8 @@ tpm2_unseal()
 	|| return $?
 
 	# Successfully unsealed, extend the bootmode PCR
-	log "TPM disk key unsealed"
-	/usr/sbin/tpm2 pcrextend >&2 "$BOOTMODE_PCR:sha256=$(sha256 postboot)"
+	warn "TPM disk key unsealed"
+	tpm2 pcrextend >&2 "$BOOTMODE_PCR:sha256=$(echo postboot | sha256)"
 	cat /tmp/secret.bin
 	rm /tmp/secret.bin
 	exit 0
