Don't compress the incompressible? (#127)

diff --git a/sbin/tpm2-attest b/sbin/tpm2-attest
--- a/sbin/tpm2-attest
+++ b/sbin/tpm2-attest
@@ -88,12 +88,12 @@ unpack-quote()
 {
 	QUOTE_TAR="$1"
 	if [ -z "$QUOTE_TAR" ]; then
-		die "unpack-quote: needs an quote.tgz"
+		die "unpack-quote: needs an quote.tar"
 	fi
 
 	# Check to see if a quote has already been unpacked
 	if [ ! -r "$TMP/ek.pub" ]; then
-		tar -zxf "$QUOTE_TAR" -C "$TMP" \
+		tar -xf "$QUOTE_TAR" -C "$TMP" \
 		|| die "unpack-quote: $QUOTE_TAR failed"
 	fi
 
@@ -110,8 +110,8 @@ quote_usage='
 ## quote
 Usage:
 ```
-tpm2-attest quote [nonce] > quote.tgz
-scp quote.tgz ...
+tpm2-attest quote [nonce] > quote.tar
+scp quote.tar ...
 ```
 After contacting the remote attestation server to receive the
 nonce, the machine will generate the endorsement key,
@@ -119,7 +119,7 @@ endorsement cert, a one-time attestation key, and a signed quote
 for the all PCRs using that nonce (or the time of day, if no nonce
 is supplied).
 
-The output `quote.tgz` should be sent to the remote side for validation.
+The output `quote.tar` should be sent to the remote side for validation.
 There is nothing sensitive in the file, so it can be sent in clear text
 to the server.
 
@@ -266,17 +266,17 @@ quote()
 		-cf - \
 		-C "$TMP" \
 		"${QUOTE_FILES[@]}" \
-	| gzip -f > "$TMP/quote.tgz" \
-	|| die "$TMP/quote.tgz: Unable to create"
+	> "$TMP/quote.tar" \
+	|| die "$TMP/quote.tar: Unable to create"
 
 	# ensure that this quote validates locally before
 	# sending it to the attestation server.
 	quote-verify >&2 \
-		"$TMP/quote.tgz" \
+		"$TMP/quote.tar" \
 		"$QUOTE_NONCE" \
 	|| die "unable to self-verify quote"
 
-	cat "$TMP/quote.tgz" || die "quote.tgz: unable to display"
+	cat "$TMP/quote.tar" || die "quote.tar: unable to display"
 }
 
 attest_usage='
@@ -306,7 +306,7 @@ attest()
 
 	SERVER="$1" ; shift
 
-	quote "$@" > "$TMP/quote-out.tgz" \
+	quote "$@" > "$TMP/quote-out.tar" \
 	|| die "Unable to create quote"
 
 	warn "$SERVER: sending attestation"
@@ -315,12 +315,12 @@ attest()
 		-X POST \
 		--fail \
 		--silent \
-		--data-binary @"$TMP/quote-out.tgz" \
-		--output "$TMP/cipher.tgz" \
+		--data-binary @"$TMP/quote-out.tar" \
+		--output "$TMP/cipher.tar" \
 		"$SERVER" \
 	|| die "attestation failed"
 
-	unseal < "$TMP/cipher.tgz" \
+	unseal < "$TMP/cipher.tar" \
 	|| die "unsealing failed"
 }
 
@@ -331,7 +331,7 @@ verify_usage='
 ## verify
 Usage:
 ```
-tpm2-attest verify quote.tgz [nonce [ca-path]]
+tpm2-attest verify quote.tar [nonce [ca-path]]
 ```
 
 This will validate that the quote was signed with the attestation key
@@ -438,7 +438,7 @@ eventlog_verify_usage='
 ## eventlog-verify
 Usage:
 ```
-tpm2-attest eventlog-verify quote.tgz [good-pcrs.txt]
+tpm2-attest eventlog-verify quote.tar [good-pcrs.txt]
 ```
 
 This will verify that the PCRs included in the quote match the
@@ -486,7 +486,7 @@ ek_verify_usage='
 ## ek-verify
 Usage:
 ```
-tpm2-attest ek-verify quote.tgz ca-path
+tpm2-attest ek-verify quote.tar ca-path
 ```
 
 This will validate that the endorsement key came from a valid TPM.
@@ -583,7 +583,7 @@ quote_verify_usage='
 ## quote-verify
 Usage:
 ```
-tpm2-attest quote-verify quote.tgz [nonce]
+tpm2-attest quote-verify quote.tar [nonce]
 ```
 
 This command checks that the quote includes the given nonce and
@@ -675,7 +675,7 @@ seal_usage='
 ## seal
 Usage:
 ```
-echo secret | tpm2-attest seal quote.tgz > cipher.bin
+echo secret | tpm2-attest seal quote.tar > cipher.bin
 ```
 
 After a attested quote has been validated, an encrypted reply is sent to
@@ -685,8 +685,8 @@ with that machines endorsment key (`ek.crt`), along with the name
 of the attestation key used to sign the quote.  The TPM will not decrypt
 the message key unless the attestation key was one that it generated.
 
-The `sealed.tgz` file should be sent back to the device being attested;
-it can then run `tpm2-attest unseal < sealed.tgz > secret.txt`
+The `sealed.tar` file should be sent back to the device being attested;
+it can then run `tpm2-attest unseal < sealed.tar > secret.txt`
 to extract the sealed secret (which may be of arbitrary length).
 '
 usage+="$seal_usage"
@@ -732,7 +732,7 @@ seal()
 	fi
 
 	# and output the sealed secret, plus the data that has been encrypted with it
-	tar -C "$TMP" -zcf - credential.bin cipher.bin ak.ctx
+	tar -C "$TMP" -cf - credential.bin cipher.bin ak.ctx
 }
 
 ########################################
@@ -741,7 +741,7 @@ unseal_usage='
 ## unseal
 Usage:
 ```
-cat sealed.tgz | tpm2-attest unseal > secret.txt
+cat sealed.tar | tpm2-attest unseal > secret.txt
 ```
 
 When the remote attestation has been successful, the remote machine will
@@ -765,7 +765,7 @@ unseal()
 		--key-algorithm "rsa" \
 	|| die "tpm2_createek: unable to create EK context"
 
-	tar -C "$TMP" -zxf - \
+	tar -C "$TMP" -xf - \
 	|| die "Unable to extract sealed secret tar file"
 
 	tpm2_secret_session "$TMP/session.ctx"
@@ -792,7 +792,7 @@ verify_and_seal_usage='
 ## verify-and-seal
 Usage:
 ```
-tpm2-attest verify-and-seal quote.tgz [nonce [pcrs]] < secret.txt > sealed.tgz
+tpm2-attest verify-and-seal quote.tar [nonce [pcrs]] < secret.txt > sealed.tar
 ```
 
 If the `nonce` is not specified on the command line, the one in the
