tpm2-attest: split validate into separate quote-validate, ek-validate, and eventlog-validate

diff --git a/sbin/tpm2-attest b/sbin/tpm2-attest
--- a/sbin/tpm2-attest
+++ b/sbin/tpm2-attest
@@ -40,6 +40,8 @@ usage='
 
 Usage: `tpm2-attest subcommand [options...]`
 
+For more information see: <https://safeboot.dev/attestation/>
+
 '
 
 commands="commands"
@@ -68,6 +70,21 @@ tpm2_flush_all()
 	tpm2_flushcontext \
 		--loaded-session \
 	|| die "tpm2_flushcontext: unable to flush sessions"
+}
+
+unpack_tar()
+{
+	QUOTE_TAR="$1"
+	if [ -z "$QUOTE_TAR" ]; then
+		warn "unpack_tar needs an quote.tgz"
+		return 1
+	fi
+	if [ ! -r "$TMP/ek.crt" ]; then
+		tar -zxvf "$QUOTE_TAR" -C "$TMP" \
+		|| return 1
+	fi
+
+	# check for the common files?
 }
 
 
@@ -178,10 +195,9 @@ quote()
 	|| die "$TMP/quote.tgz: Unable to create"
 
 	# ensure that this quote validates
-	validate \
+	quote-validate \
 		"$TMP/quote.tgz" \
 		"$QUOTE_NONCE" \
-		"$TMP/validate" \
 	|| die "unable to self-validate quote"
 
 	mv "$TMP/quote.tgz" "." || die "quote.tgz: unable to move"
@@ -189,37 +205,121 @@ quote()
 
 ########################################
 
+validate_usage='
+## validate
+Usage:
+```
+tpm2-attest validate quote.tgz [nonce [ca-path]]
+```
+
+This will validate that the quote was signed with the attestation key
+with the provided nonce, and verify that the endorsement key from a valid
+TPM.
+
+If the `nonce` is not specified, the one in the quote file will be used,
+although this opens up the possibility of a replay attack.
+
+If the `ca-path` is not specified, the system one will be used.
+
+* TODO: validate event log
+'
+usage+="$validate_usage"
+commands+="|validate"
+
+validate()
+{
+	show_help "$1" "$validate_usage"
+	if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
+		die "Wrong arguments.$validate_usage"
+	fi
+
+	QUOTE_TAR="$1"
+	NONCE="${2:-}"
+	CA_ROOT="${3:-$PREFIX$DIR/certs}"
+
+	unpack-quote "$QUOTE_TAR" \
+	|| die "$QUOTE_TAR: unable to unpack"
+
+	quote-validate "$QUOTE_TAR" "$NONCE" \
+	|| die "$QUOTE_TAR: unable to validate quote"
+
+	ek-validate "$QUOTE_TAR" "$CA_ROOT" \
+	|| die "$QUOTE_TAR: unable to validate EK certificate"
+
+	eventlog-validate "$QUOTE_TAR" \
+	|| die "$QUOTE_TAR: unable to validate TPM event log"
+}
+
+########################################
+
+eventlog_validate_usage='
+## eventlog-validate
+Usage:
+```
+tpm2-attest eventlog-validate quote.tgz
+```
+
+This will validate that the PCRs included in the quote match the
+TPM event log.
+
+* TODO: build tpm2_eventlog so that these events can be parsed.
+'
+usage+="$eventlog_validate_usage"
+commands+="|eventlog-validate"
+
+eventlog-validate()
+{
+	show_help "$1" "$eventlog_validate_usage"
+	if [ "$#" -ne 1 ]; then
+		die "Wrong arguments.$eventlog_validate_usage"
+	fi
+
+	QUOTE_TAR="$1"
+
+	unpack_quote "$QUOTE_TAR" \
+	|| die "$QUOTE_TAR: Unable to unpack"
+
+	warn "$QUOTE_TAR: eventlog parsing is not yet functional"
+}
+
+
+########################################
+
 ek_validate_usage='
 ## ek-validate
 Usage:
 ```
-tpm2-attest ek-validate quote.tgz ca-root ca-path
+tpm2-attest ek-validate quote.tgz ca-path
 ```
 
-The TPM endorsement key is signed by the manufacturer OEM key, which is
-in turn signed by a root CA.  Before trusting an attestation it is
-necessary to validate this chain of signatures to ensure that it came
-from a legitimate TPM.
+This will validate that the endorsement key came from a valid TPM.
 
-It is also necessary to validate that the `ek.pub` and `ek.pem`
-have the modulus since they are in two files.
+The TPM endorsement key is signed by the manufacturer OEM key, which is
+in turn signed by a trusted root CA.  Before trusting an attestation it is
+necessary to validate this chain of signatures to ensure that it came
+from a legitimate TPM, otherwise an attacker could send a quote that
+has a fake key and decrypt the message in software.
+
+The `ca-path` should contain a file named `roots.pem` with the trusted
+root keys and have the hash symlinks created by `c_rehash`.
+
+* TODO: check parameters of attestation key.
 '
 usage+="$ek_validate_usage"
 commands+="|ek-validate"
 
 ek-validate()
 {
-	show_help "$1" "$ek-validate_usage"
-	if [ "$#" -lt 3 ]; then
-		die "Insufficent arguments.$ek_validate_usage"
+	show_help "$1" "$ek_validate_usage"
+	if [ "$#" -ne 2 ]; then
+		die "Wrong arguments.$ek_validate_usage"
 	fi
 
 	QUOTE_TAR="$1"
-	CA_ROOT="$2"
-	CA_PATH="$3"
+	CA_PATH="$2"
 
-	tar -zxf "$QUOTE_TAR" -C "$TMP" \
-	|| die "$QUOTE_TAR: unable to extract"
+	unpack_quote "$QUOTE_TAR" \
+	|| die "$QUOTE_TAR: Unable to unpack"
 
 	# convert the DER into a PEM since 'openssl verify' only works with PEM
 	openssl x509 \
@@ -246,7 +346,7 @@ ek-validate()
 		-noout \
 		-modulus \
 		| cut -d= -f2 \
-		| tr '[A-Z]' '[a-z]')"
+		| tr 'A-F' 'a-f')"
 
 	if [ "$mod1" != "$mod2" ]; then
 		warn "ek.pub: $mod1"
@@ -257,20 +357,17 @@ ek-validate()
 	warn "ek.pub: matches ek.crt!"
 }
 
-
-########################################
-
-validate_usage='
-## validate
+quote_validate_usage='
+## quote-validate
 Usage:
 ```
-tpm2-attest validate quote.tgz [nonce]
+tpm2-attest quote-validate quote.tgz [nonce]
 ```
 
-This command only checks that the quote includes the given nonce and
-was signed by the public attestation key (AK).  It does not validate that
-the AK came from a valid TPM.  That is done in the `tpm2-attest ek-validate`
-subcommand.
+This command checks that the quote includes the given nonce and
+was signed by the public attestation key (AK) in the quote file.
+NOTE: This does not validate that the AK came from a valid TPM.
+See `tpm2-attest validate` for the full validation.
 
 If the `nonce` is not specified on the command line, the one in the
 quote file will be used.  Note that this is a potential for a replay
@@ -278,34 +375,30 @@ attack -- the remote attestation server should keep track of which
 nonce it used for this quote so that it can verify that the quote
 is actually live.
 '
-usage+="$validate_usage"
-commands+="|validate"
+usage+="$quote_validate_usage"
+commands+="|quote-validate"
 
-validate()
+quote-validate()
 {
-	show_help "$1" "$validate_usage"
+	show_help "$1" "$quote_validate_usage"
 	if [ "$#" -lt 1 ]; then
-		die "Insufficent arguments.$validate_usage"
+		die "Insufficent arguments.$quote_validate_usage"
 	fi
 
 	QUOTE_TAR="$1"
 	QUOTE_NONCE="${2:-}"
-	DIR="${3:-$TMP}"
 
-	mkdir -p "$DIR" || die "$DIR"
-	warn "$QUOTE_TAR: validating into $DIR"
+	unpack-quote "$QUOTE_TAR" \
+	|| die "$QUOTE_TAR: unable to unpack"
 	
-	tar -zxf "$QUOTE_TAR" -C "$DIR" \
-	|| die "$QUOTE_TAR: unable to extract"
-
 	tpm2_print \
 		-t "TPMS_ATTEST" \
-		"$DIR/quote.out" \
+		"$TMP/quote.out" \
 	|| die "tpm2_print: unable to parse quote"
 
 	if [ "$QUOTE_NONCE" = "" ]; then
 		# if no nonce was specified, read it from the tar file
-		QUOTE_NONCE="$(cat "$DIR/nonce")"
+		QUOTE_NONCE="$(cat "$TMP/nonce")"
 	fi
 
 	# convert the TPMT formatted attestation key into a DER public
@@ -313,23 +406,23 @@ validate()
 	# tpm2_checkquote can work with it (due to this issue):
 	# https://github.com/tpm2-software/tpm2-tools/issues/2049
 	( \
-		echo 30820122300d06092a864886f70d0101 | hex2bin ; \
-		echo 0105000382010f003082010a0282010100 | hex2bin ; \
-		tail -c 256 "$DIR/ak.pub" ; \
-		echo 0203010001 | hex2bin ; \
+		echo 30820122300d06092a864886f70d0101 | hex2bin - ; \
+		echo 0105000382010f003082010a0282010100 | hex2bin - ; \
+		tail -c 256 "$TMP/ak.pub" ; \
+		echo 0203010001 | hex2bin - ; \
 	) | openssl rsa \
 		-pubin \
 		-inform "DER" \
 		-outform "PEM" \
-		-out "$DIR/ak.pem" \
-	|| die "$DIR/ak.pub: unable to convert to ak.pem"
+		-out "$TMP/ak.pem" \
+	|| die "$TMP/ak.pub: unable to convert to ak.pem"
 
 	tpm2_checkquote \
 		--qualification "$QUOTE_NONCE" \
-		--message "$DIR/quote.out" \
-		--signature "$DIR/quote.sig" \
-		--pcr "$DIR/quote.pcr" \
-		--public "$DIR/ak.pem" \
+		--message "$TMP/quote.out" \
+		--signature "$TMP/quote.sig" \
+		--pcr "$TMP/quote.pcr" \
+		--public "$TMP/ak.pem" \
 	|| die "$QUOTE_TAR: unable to validate quote with '$QUOTE_NONCE'"
 }
 
@@ -365,12 +458,6 @@ seal()
 	QUOTE_TAR="$1"
 	QUOTE_NONCE="${2:-}"
 
-	validate \
-		"$QUOTE_TAR" \
-		"$QUOTE_NONCE" \
-		>&2 \
-	|| die "$QUOTE_TAR: quote did not validate"
-	
 	cat > "$TMP/secret" \
 	|| die "Unable to read secret data from stdin"
 
@@ -471,7 +558,7 @@ case "$command" in
 		exit 0
 		;;
 	#$commands)
-	commands|quote|ek-validate|validate|seal|unseal)
+	commands|quote|validate|validate|seal|unseal|ek-validate|quote-validate|eventlog-validate)
 		$command "$@"
 		;;
 	*)
